module rand_case;
  initial begin
    $display("Random data will be generated by simulator");
    $display("Data from 0 to 3 then it will display randcase output");
    for(int i=0;i<6;i++) begin
      randcase
      0:$display("Output of randcase 0");// Case 0 with weight 0
      1:$display("Output of randcase 1");// Case 1 with weight 1
      2:$display("Output of randcase 2");// Case 2 with weight 2
      4:$display("Output of randcase 3");// Case 0 with weight 3
      endcase
    end
  end
endmodule

// OUTPUT
Random data will be generated by simulator
Data from 0 to 3 then it will display randcase output
Output of randcase 1
Output of randcase 2
Output of randcase 3
Output of randcase 2
Output of randcase 3
Output of randcase 3
